# Redis cache package - reusable Redis configuration
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
    healthcheck:
      command: "redis-cli ping"
    restart: always
